package com.sg.cristina.dao;

import com.sg.cristina.entity.SgUser;
import org.apache.ibatis.annotations.Mapper;

//@Mapper
public interface SgUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sg_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer sgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sg_user
     *
     * @mbggenerated
     */
    int insert(SgUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sg_user
     *
     * @mbggenerated
     */
    int insertSelective(SgUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sg_user
     *
     * @mbggenerated
     */
    SgUser selectByPrimaryKey(Integer sgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sg_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SgUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sg_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SgUser record);
}