package com.sg.cristina.dao;

import com.sg.cristina.entity.SgUser;
import org.apache.ibatis.annotations.Select;

//@Mapper
public interface SgUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sg_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer sgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sg_user
     *
     * @mbggenerated
     */
    int insert(SgUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sg_user
     *
     * @mbggenerated
     */
    int insertSelective(SgUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sg_user
     *
     * @mbggenerated
     */
    SgUser selectByPrimaryKey(Integer sgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sg_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SgUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sg_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SgUser record);


    /**
     * select user by gitId
     * @param gitId
     * @return
     */
    @Select("select 8 from sg_user where git_id = #{gitId}")
    SgUser selectByGitId(String gitId);
}