package com.sg;

import javax.persistence.*;
import java.io.Serializable;
import java.util.Objects;

@Entity
@Table(name="sg_user")
public class SgUser  implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sg_user.sg_id
     *
     * @mbggenerated
     */
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name = "sg_id")
    private Integer sgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sg_user.username
     *
     * @mbggenerated
     */
    @Column
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sg_user.password
     *
     * @mbggenerated
     */
    @Column
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sg_user.mobile
     *
     * @mbggenerated
     */
    @Column
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sg_user.git_id
     *
     * @mbggenerated
     */
    @Column
    private String gitId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sg_user.idcard
     *
     * @mbggenerated
     */
    @Column
    private String idcard;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sg_user.sg_id
     *
     * @return the value of sg_user.sg_id
     *
     * @mbggenerated
     */
    public Integer getSgId() {
        return sgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sg_user.sg_id
     *
     * @param sgId the value for sg_user.sg_id
     *
     * @mbggenerated
     */
    public void setSgId(Integer sgId) {
        this.sgId = sgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sg_user.username
     *
     * @return the value of sg_user.username
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sg_user.username
     *
     * @param username the value for sg_user.username
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sg_user.password
     *
     * @return the value of sg_user.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sg_user.password
     *
     * @param password the value for sg_user.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sg_user.mobile
     *
     * @return the value of sg_user.mobile
     *
     * @mbggenerated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sg_user.mobile
     *
     * @param mobile the value for sg_user.mobile
     *
     * @mbggenerated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sg_user.git_id
     *
     * @return the value of sg_user.git_id
     *
     * @mbggenerated
     */
    public String getGitId() {
        return gitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sg_user.git_id
     *
     * @param gitId the value for sg_user.git_id
     *
     * @mbggenerated
     */
    public void setGitId(String gitId) {
        this.gitId = gitId == null ? null : gitId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sg_user.idcard
     *
     * @return the value of sg_user.idcard
     *
     * @mbggenerated
     */
    public String getIdcard() {
        return idcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sg_user.idcard
     *
     * @param idcard the value for sg_user.idcard
     *
     * @mbggenerated
     */
    public void setIdcard(String idcard) {
        this.idcard = idcard == null ? null : idcard.trim();
    }

    public SgUser() {
    }

    public SgUser(String username, String password, String mobile) {
        this.username = username;
        this.password = password;
        this.mobile = mobile;
    }

    @Override
    public String toString() {
        return "SgUser{" +
                "sgId=" + sgId +
                ", username='" + username + '\'' +
                ", password='" + password + '\'' +
                ", mobile='" + mobile + '\'' +
                ", gitId='" + gitId + '\'' +
                ", idcard='" + idcard + '\'' +
                '}';
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        SgUser user = (SgUser) o;
        return Objects.equals(sgId, user.sgId) &&
                Objects.equals(username, user.username) &&
                Objects.equals(password, user.password) &&
                Objects.equals(mobile, user.mobile) &&
                Objects.equals(gitId, user.gitId) &&
                Objects.equals(idcard, user.idcard);
    }

    @Override
    public int hashCode() {
        return Objects.hash(sgId, username, password, mobile, gitId, idcard);
    }
}