package com.sg.cristina.entity;

public class SgUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sg_user.sg_id
     *
     * @mbggenerated
     */
    private Integer sgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sg_user.username
     *
     * @mbggenerated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sg_user.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sg_user.mobile
     *
     * @mbggenerated
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sg_user.git_id
     *
     * @mbggenerated
     */
    private String gitId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sg_user.idcard
     *
     * @mbggenerated
     */
    private String idcard;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sg_user.sg_id
     *
     * @return the value of sg_user.sg_id
     *
     * @mbggenerated
     */
    public Integer getSgId() {
        return sgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sg_user.sg_id
     *
     * @param sgId the value for sg_user.sg_id
     *
     * @mbggenerated
     */
    public void setSgId(Integer sgId) {
        this.sgId = sgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sg_user.username
     *
     * @return the value of sg_user.username
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sg_user.username
     *
     * @param username the value for sg_user.username
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sg_user.password
     *
     * @return the value of sg_user.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sg_user.password
     *
     * @param password the value for sg_user.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sg_user.mobile
     *
     * @return the value of sg_user.mobile
     *
     * @mbggenerated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sg_user.mobile
     *
     * @param mobile the value for sg_user.mobile
     *
     * @mbggenerated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sg_user.git_id
     *
     * @return the value of sg_user.git_id
     *
     * @mbggenerated
     */
    public String getGitId() {
        return gitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sg_user.git_id
     *
     * @param gitId the value for sg_user.git_id
     *
     * @mbggenerated
     */
    public void setGitId(String gitId) {
        this.gitId = gitId == null ? null : gitId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sg_user.idcard
     *
     * @return the value of sg_user.idcard
     *
     * @mbggenerated
     */
    public String getIdcard() {
        return idcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sg_user.idcard
     *
     * @param idcard the value for sg_user.idcard
     *
     * @mbggenerated
     */
    public void setIdcard(String idcard) {
        this.idcard = idcard == null ? null : idcard.trim();
    }

    public SgUser() {
    }
}